
Option Strict On
Option Explicit On
Option Infer Off

Imports System.Drawing
Imports System.Reflection

' ============================================================================
'                    AI GENERATED BY GOOGLE GEMINI 3.1 PRO                    
' ============================================================================

''' <summary>
''' Custom ToolStripProgressBar that supports drawing custom text over the bar.
''' </summary>
Public Class TextToolStripProgressBar : Inherits ToolStripProgressBar

    Private _customText As String = "0%"

    Public Property CustomText() As String
        Get
            Return Me._customText
        End Get
        Set(value As String)
            Me._customText = value
            Me.ProgressBar.Invalidate()
        End Set
    End Property

    Public Sub New()
        MyBase.New()

        ' Target the protected 'SetStyle' method of the Control class via Reflection
        Dim setStyleMethod As MethodInfo = GetType(Control).GetMethod("SetStyle", BindingFlags.Instance Or BindingFlags.NonPublic)

        If setStyleMethod IsNot Nothing Then
            Dim styles As ControlStyles = ControlStyles.UserPaint Or ControlStyles.AllPaintingInWmPaint Or ControlStyles.OptimizedDoubleBuffer
            setStyleMethod.Invoke(Me.ProgressBar, New Object() {styles, True})
        End If

        AddHandler Me.ProgressBar.Paint, AddressOf Me.OnInternalProgressBarPaint
    End Sub

    ''' <summary>
    ''' Custom paint routine executed when the internal ProgressBar renders.
    ''' </summary>
    Private Sub OnInternalProgressBarPaint(sender As Object, e As PaintEventArgs)
        Dim g As Graphics = e.Graphics
        Dim bounds As Rectangle = Me.ProgressBar.ClientRectangle

        ' 1. Render the control background
        If ProgressBarRenderer.IsSupported Then
            ProgressBarRenderer.DrawHorizontalBar(g, bounds)
        Else
            g.FillRectangle(SystemBrushes.Control, bounds)
        End If

        ' 2. Retrieve the native properties to calculate the exact progress
        Dim currentMin As Integer = Me.Minimum
        Dim currentMax As Integer = Me.Maximum
        Dim currentValue As Integer = Me.Value

        ' 3. Render the progress chunks respecting Minimum and Maximum correctly
        If currentMax > currentMin AndAlso currentValue > currentMin Then
            ' Calculate the actual range and current progress offset
            Dim range As Double = (currentMax - currentMin)
            Dim progressOffset As Double = currentValue - currentMin
            Dim percentage As Double = progressOffset / range

            Dim progressWidth As Integer = CInt(percentage * bounds.Width)

            If progressWidth > 0 Then
                Dim progressBounds As New Rectangle(0, 0, progressWidth, bounds.Height)

                If ProgressBarRenderer.IsSupported Then
                    ProgressBarRenderer.DrawHorizontalChunks(g, progressBounds)
                Else
                    g.FillRectangle(SystemBrushes.Highlight, progressBounds)
                End If
            End If
        End If

        ' 4. Render the custom text centered directly on top of the bar
        Using textFont As New Font("Arial", 9.0F, FontStyle.Bold)
            Dim textSize As SizeF = g.MeasureString(Me._customText, textFont)
            Dim textX As Single = (bounds.Width - textSize.Width) / 2.0F
            Dim textY As Single = (bounds.Height - textSize.Height) / 2.0F

            g.DrawString(Me._customText, textFont, Brushes.Black, textX, textY)
        End Using

    End Sub

End Class